core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import *


app_name= 'orders'

urlpatterns=[
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>', OrderDetailView.as_view(), name='order_detail'),
    path('cart/', CartView.as_view() , name='cart'),
    path('cart/add/<int:product_id>/',CartAddView.as_view() , name='cart_add'),
    path('cart/remove/<int:product_id>/' , CartRemoveView.as_view() , name='cart_remove'),
]

orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from home.models import Product

class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders')
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('paid', '-updated')

    def __str__(self):
        return f'{self.user} - str({self.id})'

    def get_total_price(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity= forms.IntegerField(min_value=1 , max_value=11)
    

orders/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.views import View
from .cart import Cart
from home.models import Product
from .forms import CartAddForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order , OrderItem

# Create your views here.
class CartView(View):
    def get(self , request):
        cart=Cart(request)
        return render(request , 'orders/cart.html' ,{'cart':cart})


class CartAddView(View):
    def post(self , request , product_id):
        cart=Cart(request)
        product=get_object_or_404(Product , id=product_id)
        form=CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product , form.cleaned_data['quantity'])
        return redirect('orders:cart')
    

class CartRemoveView(View):
    def get(self,request,product_id):
        cart=Cart(request)
        product=get_object_or_404(Product,id=product_id)
        cart.remove(product)
        return redirect('orders:cart')
    

class OrderCreateView(LoginRequiredMixin,View):
    def get(self,request):
        cart=Cart(request)
        order=Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(order=order , product=item['product'] , price=item['price'],
                                     quantity=item['quantity'])
            
        cart.clear()
        return redirect('orders:order_detail' , order.id)



class OrderDetailView(LoginRequiredMixin,View):
    def get(self , request,order_id):
        order=get_object_or_404(Order , id=order_id)
        return render(request, 'orders/order.html' , {'order':order})

orders/templates/orders/cart.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-dark table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Total Price</th>
        <th scope="col">Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{item.product}}</td>
        <td>{{item.quantity}}</td>
        <td>{{item.price}}</td>
        <td>{{item.total_price}}</td> 
        <td><a href="{% url 'orders:cart_remove' item.product.id %}">remove</a></td>

        
      </tr>
      {% endfor %}

      <tr>
        <td>Tatal</td>
        <td colspan="4"></td>
        <td>{{ cart.get_total_price }}</td>
      </tr>
     
    </tbody>
  </table>

<a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>
{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}
{% block content %}
    <h3> Checkout</h3>
    <p>Total :{{order.get_total_price}}</p>

{% endblock %}