accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns =[
    path('register/',views.UserRegisterView.as_view() , name='Register'),
    path('verify/',views.UserVerifyView.as_view(), name='Verify'),
    path('login/' , views.LoginView.as_view(), name='Login'),
    path('logout/' , views.LogoutView.as_view(), name='Logout'),

]

core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
    path('',views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>',views.HomeView.as_view(), name='category_filter'),
    path('<slug:slug>/', views.ProductDetailView.as_view() , name='product_detail'),
]

templates/inc/messages.html
{% if messages%}

    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{ msg }}</p>
    {% endfor %}


{% endif%}

templates/inc/navbar.html
<nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">

    <div class="container-fluid">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'accounts:Logout' %}">Logout</a>
        {% else %}
       <a class="navbar-brand" href="{% url 'accounts:Register' %}">Register</a>
       <a class="navbar-brand" href="{% url 'accounts:Login' %}">Login</a>
       {% endif %}
       <a class="navbar-brand active " href="{% url 'home:home' %}">Cart {{cart|length}}</a>
     </div>
    </div>
  </nav>